// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  call_to_action: dynamic(() => import("./CallToAction")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  hero_2: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
